export const COPY = {
  app_name: 'Aegis-IDX',
  disclaimer_short:
    'Bukan saran investasi. Data transaksi broker dan free float untuk analisis faktual.',
  disclaimer_long:
    'Aegis-IDX bukan penasihat investasi. Tidak ada rekomendasi beli atau jual. Keputusan transaksi menjadi tanggung jawab Anda.',

  ticker_placeholder: 'BBCA',
  ticker_label: 'Kode',
  cta_investigate: 'Periksa',
  cta_retry: 'Mulai ulang',
  cta_copy: 'Salin',
  cta_copied: 'Tersalin',
  cta_close: 'Tutup',
  cta_try_example: 'Coba contoh: BBCA',
  cta_view_all: 'Daftar emiten',
  cta_expand: 'Tampilkan semua',
  cta_collapse: 'Ringkas',
  loading: 'Memproses…',
  search_hint: 'Kode 2–5 huruf, contoh BBCA',
  search_error_chars: 'Gunakan huruf dan angka saja, contoh BBCA',
  search_error_length: 'Kode efek 2–5 karakter, contoh BBCA',

  step_planner: 'Menyusun permintaan data broker dan free float',
  step_executor_broker: 'Mengambil ringkasan transaksi broker',
  step_executor_ff: 'Mengambil data kepemilikan publik',
  step_critic: 'Memeriksa netralitas data dan penafian',

  buyers_title: 'Pembeli bersih terbesar',
  sellers_title: 'Penjual bersih terbesar',
  free_float_title: 'Saham beredar di publik',
  free_float_compliant: 'Memenuhi aturan min. 7,5%',
  free_float_noncompliant: 'Di bawah aturan min. 7,5%',
  free_float_unknown: 'Data belum tersedia',
  narrative_title: 'Ringkasan',
  narrative_empty: 'Belum ada ringkasan untuk kode ini.',
  empty_title: 'Tidak ada data transaksi',
  empty_body: 'Kode ini tidak punya catatan transaksi broker, atau belum terdaftar di daftar kami.',
  empty_suggest: 'Coba kode lain atau kembali ke contoh yang pasti ada datanya.',
  idle_hint: 'Masukkan kode efek, lalu baca siapa yang paling banyak beli, siapa yang paling banyak jual, dan berapa saham yang beredar di publik.',
  toast_live_fail: 'Koneksi langsung gagal. Menampilkan data simulasi.',
  toast_copied: 'Ringkasan disalin',
  toast_copy_fail: 'Gagal menyalin. Coba lagi.',
  broker_section_hint: 'Nilai = total beli dikurangi total jual per sekuritas.',
  cr_explain: 'Angka ini porsi 3 dan 5 sekuritas terbesar dibanding daftar yang tampil (biasanya 5 baris), bukan seluruh pasar. 5 besar di daftar penuh hampir selalu 100%.',
  concentration_high: 'Terpusat',
  concentration_low: 'Menyebar',
  foreign_label: 'Asing',
  domestic_label: 'Domestik',
  net_label: 'Selisih bersih',
  buy_label: 'Beli',
  sell_label: 'Jual',

  mode_mock: 'Simulasi',
  mode_cache: 'Tersimpan',
  mode_live: 'Langsung',
  mode_hint_mock: 'Simulasi, 0 kredit',
  mode_hint_live: 'Langsung, kuota API',
  mode_hint_cache: 'Tersimpan, data lokal',
} as const;
