export const COPY = {
  disclaimer_long:
    'Aegis-IDX bukan penasihat investasi. Tidak ada rekomendasi beli atau jual. Keputusan transaksi menjadi tanggung jawab Anda.',

  ticker_placeholder: 'BBCA',
  cta_investigate: 'Periksa',
  cta_retry: 'Mulai ulang',
  cta_copy: 'Salin',
  cta_copied: 'Tersalin',
  cta_try_example: 'Coba contoh: BBCA',
  cta_view_all: 'Cari emiten',
  audit_title: 'Jejak pemeriksaan',
  cta_expand: 'Tampilkan semua',
  cta_collapse: 'Ringkas',
  loading: 'Memproses…',
  search_hint: 'Kode efek 2–5 karakter, contoh BBCA.',
  search_error_chars: 'Gunakan huruf dan angka saja, contoh BBCA',
  search_error_length: 'Kode efek 2–5 karakter, contoh BBCA',

  step_planner: 'Menyusun permintaan data broker dan free float',
  step_executor_broker: 'Mengambil ringkasan transaksi broker',
  step_executor_ff: 'Mengambil data kepemilikan publik',
  step_critic: 'Memeriksa netralitas data dan penafian',

  role_planner: 'Perencana',
  role_executor: 'Eksekutor',
  role_critic: 'Peninjau',
  orchestration_title: 'Tahapan pemeriksaan',

  buyers_title: 'Pembeli bersih terbesar',
  sellers_title: 'Penjual bersih terbesar',
  free_float_title: 'Saham beredar di publik',
  free_float_compliant: 'Memenuhi aturan min. 7,5%',
  free_float_noncompliant: 'Di bawah aturan min. 7,5%',
  free_float_unknown: 'Data belum tersedia',
  narrative_title: 'Ringkasan',
  narrative_empty: 'Belum ada ringkasan untuk kode ini.',
  empty_title: 'Tidak ada data transaksi',
  empty_body: 'Tidak ada catatan broker untuk kode ini, atau kodenya tidak ada di daftar.',
  empty_suggest: 'Coba BBCA, atau kode lain.',
  toast_live_fail: 'Koneksi langsung gagal. Menampilkan data simulasi.',
  toast_cache_miss: 'Data tersimpan tidak ada. Menampilkan simulasi.',
  toast_copied: 'Ringkasan disalin',
  toast_copy_fail: 'Gagal menyalin. Coba lagi.',
  broker_section_hint: 'Net = total beli dikurangi total jual per sekuritas.',
  cr_label: 'Porsi 3 sekuritas teratas',
  cr_explain:
    'Porsi 3 sekuritas terbesar dibanding 5 sekuritas yang tampil di daftar ini, bukan dibanding seluruh pasar.',
  foreign_label: 'Asing',
  domestic_label: 'Domestik',
  net_label: 'Selisih bersih',
  buy_label: 'Beli',
  sell_label: 'Jual',

  mode_mock: 'Simulasi',
  mode_cache: 'Tersimpan',
  mode_live: 'Langsung',
  mode_hint_mock: 'Simulasi, 0 kredit',
  mode_hint_live: 'Langsung, kuota API',
  mode_hint_cache: 'Tersimpan, data lokal',
} as const;
